<html>
<head>
<meta charset="utf-8">
</head>
<body>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:30px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">ADATV&Eacute;DELMI NYILATKOZAT</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;line-height: 15pt;background-color: white;'><strong><span style="font-size:18px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&eacute;s adatkezel&eacute;si t&aacute;j&eacute;koztat&oacute; jerseytehen.hu weboldal l&aacute;togat&oacute;i &eacute;s felhaszn&aacute;l&oacute;i r&eacute;sz&eacute;re</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">1. BEVEZETŐ</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A jerseytehen.hu - a tov&aacute;bbiakban: Weblap - &uuml;zemeltetője Dombai Szandra Őstermelő (a tov&aacute;bbiakban: Adatkezelő), mint Adatkezelő jelen Adatv&eacute;delmi Nyilatkozat &eacute;s Adatkezel&eacute;si T&aacute;j&eacute;koztat&oacute; ( a tov&aacute;bbiakban: Adatv&eacute;delmi Nyilatkozat) k&ouml;zz&eacute;t&eacute;tel&eacute;vel ismerteti az adatkezel&eacute;s&eacute;re vonatkoz&oacute; elveit, melyeket az Adatkezelő mag&aacute;ra n&eacute;zve k&ouml;telező &eacute;rv&eacute;nyűnek ismer el. Az Adatkezelő minden tőle &eacute;sszerűen elv&aacute;rhat&oacute; int&eacute;zked&eacute;st megtesz az &aacute;ltala kezelt szem&eacute;lyes adatok biztons&aacute;ga &eacute;rdek&eacute;ben.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">K&eacute;rj&uuml;k, hogy Weboldal haszn&aacute;lata előtt sz&iacute;veskedjen elolvasni a jelen Adatv&eacute;delmi Nyilatkozatot, mely k&ouml;z&eacute;rthető m&oacute;don tartalmazza, mik&eacute;nt kezelj&uuml;k szem&eacute;lyes adatait! Az Adatv&eacute;delmi Nyilatkozatban az Adatkezelő egy&eacute;rtelműen &eacute;s r&eacute;szletesen t&aacute;j&eacute;koztatja az &eacute;rintetteket az adatok kezel&eacute;s&eacute;vel kapcsolatos minden fontos t&eacute;nyről.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő a weboldal műk&ouml;dtet&eacute;se sor&aacute;n, az oldalon l&aacute;togat&oacute;inak adatait kezeli abb&oacute;l a c&eacute;lb&oacute;l, hogy r&eacute;sz&uuml;kre megfelelő szolg&aacute;ltat&aacute;st ny&uacute;jthasson. A szolg&aacute;ltat&oacute; teljes m&eacute;rt&eacute;kben meg k&iacute;v&aacute;n felelni a szem&eacute;lyes adatok kezel&eacute;s&eacute;re vonatkoz&oacute; jogszab&aacute;lyi elő&iacute;r&aacute;soknak, k&uuml;l&ouml;n&ouml;sen az Eur&oacute;pai Parlament &eacute;s a Tan&aacute;cs (EU) 2016/679 rendelet&eacute;ben foglaltaknak.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Ez az adatkezel&eacute;si t&aacute;j&eacute;koztat&oacute; a term&eacute;szetes szem&eacute;lyek szem&eacute;lyes adatai v&eacute;delm&eacute;ről &eacute;s az adatok szabad &aacute;raml&aacute;s&aacute;r&oacute;l az Eur&oacute;pai Parlament &eacute;s a Tan&aacute;cs (EU) 2016/679 rendelete alapj&aacute;n k&eacute;sz&uuml;lt, figyelemmel a 2011. &eacute;vi CXII. t&ouml;rv&eacute;ny tartalm&aacute;ra, amely az inform&aacute;ci&oacute;s &ouml;nrendelkez&eacute;si jogr&oacute;l &eacute;s az inform&aacute;ci&oacute;szabads&aacute;gr&oacute;l sz&oacute;l.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;line-height: 15pt;background-color: white;'><strong><span style="font-size:18px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Szolg&aacute;ltat&oacute;, adatkezelő megnevez&eacute;se</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">N&eacute;v:&nbsp;Pell&eacute;rdi Sajtműhely &ndash; Dombai Szandra Őstermelő<br>Sz&eacute;khely:&nbsp;7831 Pell&eacute;rd, D&oacute;zsa Gy&ouml;rgy &uacute;t 56.<br>Weboldal megnevez&eacute;se, c&iacute;me: jerseytehen.hu</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;line-height: 15pt;background-color: white;'><strong><span style="font-size:18px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezelő el&eacute;rhetős&eacute;gei</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">N&eacute;v:&nbsp;Pell&eacute;rdi Sajtműhely &ndash; Dombai Szandra Őstermelő<br>Sz&eacute;khely:&nbsp;7831 Pell&eacute;rd, D&oacute;zsa Gy&ouml;rgy &uacute;t 56.<br>Weboldal megnevez&eacute;se, c&iacute;me: jerseytehen.hu<br>E-mail :</span><u><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(0, 122, 197);">szandra@jerseytehen.hu</span></u><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);"><br>Telefon:&nbsp;+36 70/6099 910</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">2. FOGALOM MEGHAT&Aacute;ROZ&Aacute;SOK</span></strong></p>
<ul style="margin-bottom: 0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">szem&eacute;lyes adat: azonos&iacute;tott vagy azonos&iacute;that&oacute; term&eacute;szetes szem&eacute;lyre (&eacute;rintett) vonatkoz&oacute; b&aacute;rmely inform&aacute;ci&oacute;; azonos&iacute;that&oacute; az a term&eacute;szetes szem&eacute;ly, aki k&ouml;zvetlen vagy k&ouml;zvetett m&oacute;don, k&uuml;l&ouml;n&ouml;sen valamely azonos&iacute;t&oacute;, p&eacute;ld&aacute;ul n&eacute;v, sz&aacute;m, helymeghat&aacute;roz&oacute; adat, online azonos&iacute;t&oacute; vagy a term&eacute;szetes szem&eacute;ly testi, fiziol&oacute;giai, genetikai, szellemi, gazdas&aacute;gi, kultur&aacute;lis vagy szoci&aacute;lis azonoss&aacute;g&aacute;ra vonatkoz&oacute; egy vagy t&ouml;bb t&eacute;nyező alapj&aacute;n azonos&iacute;that&oacute;;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">&eacute;rintett: b&aacute;rmely meghat&aacute;rozott, szem&eacute;lyes adat alapj&aacute;n azonos&iacute;tott vagy &ndash; k&ouml;zvetlen&uuml;l vagy k&ouml;zvetve &ndash; azonos&iacute;that&oacute; term&eacute;szetes szem&eacute;ly</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">az &eacute;rintett hozz&aacute;j&aacute;rul&aacute;sa: az &eacute;rintett akarat&aacute;nak &ouml;nk&eacute;ntes, konkr&eacute;t &eacute;s megfelelő t&aacute;j&eacute;koztat&aacute;son alapul&oacute; &eacute;s egy&eacute;rtelmű kinyilv&aacute;n&iacute;t&aacute;sa, amellyel az &eacute;rintett nyilatkozat vagy a megerős&iacute;t&eacute;st f&eacute;lre&eacute;rthetetlen&uuml;l kifejező cselekedet &uacute;tj&aacute;n jelzi, hogy beleegyez&eacute;s&eacute;t adja az őt &eacute;rintő szem&eacute;lyes adatok kezel&eacute;s&eacute;hez;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatkezelő: az a term&eacute;szetes vagy jogi szem&eacute;ly, k&ouml;zhatalmi szerv, &uuml;gyn&ouml;ks&eacute;g vagy b&aacute;rmely egy&eacute;b szerv, amely a szem&eacute;lyes adatok kezel&eacute;s&eacute;nek c&eacute;ljait &eacute;s eszk&ouml;zeit &ouml;n&aacute;ll&oacute;an vagy m&aacute;sokkal egy&uuml;tt meghat&aacute;rozza; ha az adatkezel&eacute;s c&eacute;ljait &eacute;s eszk&ouml;zeit az uni&oacute;s vagy a tag&aacute;llami jog hat&aacute;rozza meg, az adatkezelőt vagy az adatkezelő kijel&ouml;l&eacute;s&eacute;re vonatkoz&oacute; k&uuml;l&ouml;n&ouml;s szempontokat az uni&oacute;s vagy a tag&aacute;llami jog is meghat&aacute;rozhatja.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatkezel&eacute;s: az alkalmazott elj&aacute;r&aacute;st&oacute;l f&uuml;ggetlen&uuml;l az adaton v&eacute;gzett b&aacute;rmely művelet vagy a műveletek &ouml;sszess&eacute;ge, &iacute;gy k&uuml;l&ouml;n&ouml;sen gyűjt&eacute;se, felv&eacute;tele, r&ouml;gz&iacute;t&eacute;se, rendszerez&eacute;se, t&aacute;rol&aacute;sa, megv&aacute;ltoztat&aacute;sa, felhaszn&aacute;l&aacute;sa, lek&eacute;rdez&eacute;se, tov&aacute;bb&iacute;t&aacute;sa, nyilv&aacute;noss&aacute;gra hozatala, &ouml;sszehangol&aacute;sa vagy &ouml;sszekapcsol&aacute;sa, z&aacute;rol&aacute;sa, t&ouml;rl&eacute;se &eacute;s megsemmis&iacute;t&eacute;se, valamint az adat tov&aacute;bbi felhaszn&aacute;l&aacute;s&aacute;nak megakad&aacute;lyoz&aacute;sa, f&eacute;nyk&eacute;p-, hang- vagy k&eacute;pfelv&eacute;tel k&eacute;sz&iacute;t&eacute;se, valamint a szem&eacute;ly azonos&iacute;t&aacute;s&aacute;ra alkalmas fizikai jellemzők (pl. ujj- vagy teny&eacute;rnyomat, DNS-minta, &iacute;riszk&eacute;p) r&ouml;gz&iacute;t&eacute;se</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatt&ouml;rl&eacute;s: az adat felismerhetetlenn&eacute; t&eacute;tele oly m&oacute;don, hogy a helyre&aacute;ll&iacute;t&aacute;sa t&ouml;bb&eacute; nem lehets&eacute;ges</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatfeldolgoz&oacute;: az a term&eacute;szetes vagy jogi szem&eacute;ly, k&ouml;zhatalmi szerv, &uuml;gyn&ouml;ks&eacute;g vagy b&aacute;rmely egy&eacute;b szerv, amely az adatkezelő nev&eacute;ben szem&eacute;lyes adatokat kezel;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatfeldolgoz&aacute;s: az adatkezel&eacute;si műveletekhez kapcsol&oacute;d&oacute; technikai feladatok elv&eacute;gz&eacute;se, f&uuml;ggetlen&uuml;l a műveletek v&eacute;grehajt&aacute;s&aacute;hoz alkalmazott m&oacute;dszertől &eacute;s eszk&ouml;ztől, valamint az alkalmaz&aacute;s hely&eacute;től, felt&eacute;ve hogy a technikai feladatot az adaton v&eacute;gzik</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adat&aacute;llom&aacute;ny: az egy nyilv&aacute;ntart&aacute;sban kezelt adatok &ouml;sszess&eacute;ge</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">adatv&eacute;delmi incidens: a biztons&aacute;g olyan s&eacute;r&uuml;l&eacute;se, amely a tov&aacute;bb&iacute;tott, t&aacute;rolt vagy m&aacute;s m&oacute;don kezelt szem&eacute;lyes adatok v&eacute;letlen vagy jogellenes megsemmis&iacute;t&eacute;s&eacute;t, elveszt&eacute;s&eacute;t, megv&aacute;ltoztat&aacute;s&aacute;t, jogosulatlan k&ouml;zl&eacute;s&eacute;t vagy az azokhoz val&oacute; jogosulatlan hozz&aacute;f&eacute;r&eacute;st eredm&eacute;nyezi.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">c&iacute;mzett: az a term&eacute;szetes vagy jogi szem&eacute;ly, k&ouml;zhatalmi szerv, &uuml;gyn&ouml;ks&eacute;g vagy b&aacute;rmely egy&eacute;b szerv, akivel vagy amellyel a szem&eacute;lyes adatot k&ouml;zlik, f&uuml;ggetlen&uuml;l att&oacute;l, hogy harmadik f&eacute;l-e. Azon k&ouml;zhatalmi szervek, amelyek egy egyedi vizsg&aacute;lat keret&eacute;ben az uni&oacute;s vagy a tag&aacute;llami joggal &ouml;sszhangban f&eacute;rhetnek hozz&aacute; szem&eacute;lyes adatokhoz, nem minős&uuml;lnek c&iacute;mzettnek; az eml&iacute;tett adatok e k&ouml;zhatalmi szervek &aacute;ltali kezel&eacute;se meg kell, hogy feleljen az adatkezel&eacute;s c&eacute;ljainak megfelelően az alkalmazand&oacute; adatv&eacute;delmi szab&aacute;lyoknak;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">harmadik f&eacute;l: az a term&eacute;szetes vagy jogi szem&eacute;ly, k&ouml;zhatalmi szerv, &uuml;gyn&ouml;ks&eacute;g vagy b&aacute;rmely egy&eacute;b szerv, amely nem azonos az &eacute;rintettel, az adatkezelővel, az adatfeldolgoz&oacute;val vagy azokkal a szem&eacute;lyekkel, akik az adatkezelő vagy adatfeldolgoz&oacute; k&ouml;zvetlen ir&aacute;ny&iacute;t&aacute;sa alatt a szem&eacute;lyes adatok kezel&eacute;s&eacute;re felhatalmaz&aacute;st kaptak.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">inform&aacute;ci&oacute;s t&aacute;rsadalommal &ouml;sszef&uuml;ggő szolg&aacute;ltat&aacute;s: elektronikus &uacute;ton, t&aacute;vollevők r&eacute;sz&eacute;re, rendszerint ellenszolg&aacute;ltat&aacute;s fej&eacute;ben ny&uacute;jtott szolg&aacute;ltat&aacute;s, amelyhez a szolg&aacute;ltat&aacute;s ig&eacute;nybe vevője egyedileg f&eacute;r hozz&aacute;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">elektronikus kereskedelmi szolg&aacute;ltat&aacute;s: olyan inform&aacute;ci&oacute;s t&aacute;rsadalommal &ouml;sszef&uuml;ggő szolg&aacute;ltat&aacute;s, amelynek c&eacute;lja valamely birtokba vehető forgalomk&eacute;pes ing&oacute; dolog - ide&eacute;rtve a p&eacute;nzt &eacute;s az &eacute;rt&eacute;kpap&iacute;rt, valamint a dolog m&oacute;dj&aacute;ra hasznos&iacute;that&oacute; term&eacute;szeti erőket -, szolg&aacute;ltat&aacute;s, ingatlan, vagyoni &eacute;rt&eacute;kű jog (a tov&aacute;bbiakban egy&uuml;tt: &aacute;ru) &uuml;zletszerű &eacute;rt&eacute;kes&iacute;t&eacute;se, beszerz&eacute;se, cser&eacute;je vagy m&aacute;s m&oacute;don t&ouml;rt&eacute;nő ig&eacute;nybev&eacute;tele.&nbsp;</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">GDPR (General Data Protection Regulation): az Eur&oacute;pai Uni&oacute; &uacute;j Adatv&eacute;delmi Rendelete;</span></li>
</ul>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">3. FELHASZN&Aacute;L&Oacute;K K&Ouml;RE</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Felhaszn&aacute;l&oacute; egyar&aacute;nt az oldalt l&aacute;togat&oacute;, a nem regisztr&aacute;lt, a Weblap szolg&aacute;ltat&aacute;sait ig&eacute;nybevevő, b&aacute;rmely meghat&aacute;rozott, szem&eacute;lyes adat alapj&aacute;n azonos&iacute;tott vagy - k&ouml;zvetlen&uuml;l vagy k&ouml;zvetve - azonos&iacute;that&oacute; term&eacute;szetes szem&eacute;ly.&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">4. AZ ADATKEZEL&Eacute;S &nbsp;IR&Aacute;NYELVEI</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezelő kijelenti, hogy az adatkezel&eacute;si t&aacute;j&eacute;koztat&oacute;ban foglaltak szerint v&eacute;gzi a szem&eacute;lyes adatok kezel&eacute;s&eacute;t &eacute;s betartja a vonatkoz&oacute; jogszab&aacute;lyok elő&iacute;r&aacute;sait, k&uuml;l&ouml;n&ouml;s figyelemmel az al&aacute;bbiakra:</span></p>
<ul style="margin-bottom: 0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok kezel&eacute;s&eacute;t jogszerűen &eacute;s tisztess&eacute;gesen, valamint az &eacute;rintett sz&aacute;m&aacute;ra &aacute;tl&aacute;that&oacute; m&oacute;don kell v&eacute;gezni.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok gyűjt&eacute;se csak meghat&aacute;rozott, egy&eacute;rtelmű &eacute;s jogszerű c&eacute;lb&oacute;l t&ouml;rt&eacute;nhet.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok kezel&eacute;s&eacute;nek c&eacute;lja megfelelő &eacute;s relev&aacute;ns legyen, &eacute;s csak a sz&uuml;ks&eacute;ges m&eacute;rt&eacute;kű lehet.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatoknak pontosnak &eacute;s naprak&eacute;sznek kell lenni&uuml;k. A pontatlan szem&eacute;lyes adatokat halad&eacute;ktalanul t&ouml;r&ouml;lni kell.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok t&aacute;rol&aacute;s&aacute;nak olyan form&aacute;ban kell t&ouml;rt&eacute;nnie, hogy az &eacute;rintettek azonos&iacute;t&aacute;s&aacute;t csak sz&uuml;ks&eacute;ges ideig tegye lehetőv&eacute;. A szem&eacute;lyes adatok enn&eacute;l hosszabb ideig t&ouml;rt&eacute;nő t&aacute;rol&aacute;s&aacute;ra csak akkor ker&uuml;lhet sor, ha a t&aacute;rol&aacute;s k&ouml;z&eacute;rdekű archiv&aacute;l&aacute;s c&eacute;lj&aacute;b&oacute;l, tudom&aacute;nyos &eacute;s t&ouml;rt&eacute;nelmi kutat&aacute;si c&eacute;lb&oacute;l vagy statisztikai c&eacute;lb&oacute;l t&ouml;rt&eacute;nik.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok kezel&eacute;s&eacute;t oly m&oacute;don kell v&eacute;gezni, hogy megfelelő technikai vagy szervez&eacute;si int&eacute;zked&eacute;sek alkalmaz&aacute;s&aacute;val biztos&iacute;tva legyen a szem&eacute;lyes adatok megfelelő biztons&aacute;ga, az adatok jogosulatlan vagy jogellenes kezel&eacute;s&eacute;vel, v&eacute;letlen elveszt&eacute;s&eacute;vel, megsemmis&iacute;t&eacute;s&eacute;vel vagy k&aacute;rosod&aacute;s&aacute;val szembeni v&eacute;delmet is ide&eacute;rtve.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatv&eacute;delem elveit minden azonos&iacute;tott vagy azonos&iacute;that&oacute; term&eacute;szetes szem&eacute;lyre vonatkoz&oacute; inform&aacute;ci&oacute; eset&eacute;ben alkalmazni kell.</span></li>
</ul>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">5. FONTOS ADATKEZEL&Eacute;SI INFORM&Aacute;CI&Oacute;K</span></strong></p>
<ul style="margin-bottom: 0cm;" type="disc">
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatkezel&eacute;s c&eacute;lja: kapcsolattart&aacute;s, inform&aacute;ci&oacute; &eacute;s t&ouml;bbletszolg&aacute;ltat&aacute;s ny&uacute;jt&aacute;sa.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatkezel&eacute;s jogalapja:&nbsp;az &eacute;rintett szem&eacute;ly hozz&aacute;j&aacute;rul&aacute;sa.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatkezel&eacute;sben &eacute;rintettek k&ouml;re:&nbsp;a weboldal l&aacute;togat&oacute;i, illetve akik kapcsolatfelv&eacute;tel c&eacute;lj&aacute;b&oacute;l a kapcsolati űrlapot kit&ouml;ltik.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatkezel&eacute;s időtartama &eacute;s az adatok t&ouml;rl&eacute;se:&nbsp;Az adatkezel&eacute;s időtartama mindig a konkr&eacute;t felhaszn&aacute;l&oacute;i c&eacute;l f&uuml;ggv&eacute;nye, de az adatokat halad&eacute;ktalanul t&ouml;r&ouml;lni kell, ha az eredetileg kitűz&ouml;tt c&eacute;l m&aacute;r megval&oacute;sult. Az adatkezel&eacute;shez t&ouml;rt&eacute;nő hozz&aacute;j&aacute;rul&aacute;s&aacute;t az &eacute;rintett szem&eacute;ly b&aacute;rmikor visszavonhatja a kapcsolattart&aacute;si e-mail c&iacute;mre k&uuml;ld&ouml;tt lev&eacute;lben. Amennyiben a t&ouml;rl&eacute;snek jogszab&aacute;lyi akad&aacute;lya nincs, ez esetben adatai t&ouml;rl&eacute;sre ker&uuml;lnek.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az adatok megismer&eacute;s&eacute;re jogosultak:&nbsp;az adatkezelő &eacute;s alkalmazottai.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az &eacute;rintett szem&eacute;ly k&eacute;relmezheti az adatkezelőtől a r&aacute; vonatkoz&oacute; szem&eacute;lyes adatokhoz val&oacute; hozz&aacute;f&eacute;r&eacute;st, azok helyesb&iacute;t&eacute;s&eacute;t, t&ouml;rl&eacute;s&eacute;t vagy kezel&eacute;s&eacute;nek korl&aacute;toz&aacute;s&aacute;t, &eacute;s tiltakozhat az ilyen szem&eacute;lyes adatok kezel&eacute;se ellen, valamint az &eacute;rintett adathordozhat&oacute;s&aacute;ghoz val&oacute; jog&aacute;r&oacute;l.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az &eacute;rintett szem&eacute;ly b&aacute;rmely időpontban visszavonhatja az adatkezel&eacute;si hozz&aacute;j&aacute;rul&aacute;s&aacute;t, de ez nem &eacute;rinti a visszavon&aacute;s előtt a hozz&aacute;j&aacute;rul&aacute;s alapj&aacute;n v&eacute;grehajtott adatkezel&eacute;s jogszerűs&eacute;g&eacute;t.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az &eacute;rintett szem&eacute;ly &eacute;lhet a fel&uuml;gyeleti hat&oacute;s&aacute;ghoz c&iacute;mzett panasz beny&uacute;jt&aacute;s&aacute;nak jog&aacute;val.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">Az &eacute;rintett szem&eacute;ly jogosult arra, hogy k&eacute;r&eacute;s&eacute;re az adatkezelő indokolatlan k&eacute;sedelem n&eacute;lk&uuml;l t&ouml;r&ouml;lje a r&aacute; vonatkoz&oacute; pontatlan szem&eacute;lyes adatokat, az adatkezelő pedig k&ouml;teles arra, hogy az &eacute;rintettre vonatkoz&oacute; szem&eacute;lyes adatokat indokolatlan k&eacute;sedelem n&eacute;lk&uuml;l t&ouml;r&ouml;lje, amennyiben az adatkezel&eacute;snek nincs m&aacute;s jogalapja.</span></li>
    <li style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;color:#333333;text-align:justify;background:white;'><span style="font-size:14px;font-family: Arial, sans-serif;">A szem&eacute;lyes adatok m&oacute;dos&iacute;t&aacute;sa vagy t&ouml;rl&eacute;se kezdem&eacute;nyezhető e-mailben, telefonon vagy lev&eacute;lben a fentebb megadott el&eacute;rhetős&eacute;gi lehetős&eacute;geken.</span></li>
</ul>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">6. WEBOLDALON TAL&Aacute;LHAT&Oacute; KAPCSOLATI ŰRLAP KIT&Ouml;LT&Eacute;SE</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő a weboldalon kereszt&uuml;l be&eacute;rkező kapcsolati űrlap &aacute;ltal hozz&aacute;f&eacute;rt adatokat kiz&aacute;r&oacute;lag kapcsolattart&aacute;s &eacute;s inform&aacute;ci&oacute; ny&uacute;jt&aacute;s c&eacute;lj&aacute;b&oacute;l haszn&aacute;lja fel, az adatokat adatb&aacute;zisban nem t&aacute;rolja.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">7. H&Iacute;RLEV&Eacute;L K&Uuml;LD&Eacute;S</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A weblap &uuml;zemeltetőjek&eacute;nt kijelentj&uuml;k, hogy az &aacute;ltalunk megjelentetett inform&aacute;ci&oacute;k &eacute;s ismertetők sor&aacute;n marad&eacute;ktalanul betartjuk a vonatkoz&oacute; jogszab&aacute;lyi rendelkez&eacute;seket. Kijelentj&uuml;k tov&aacute;bb&aacute;, hogy h&iacute;rlev&eacute;lre t&ouml;rt&eacute;nő feliratkoz&aacute;skor nem &aacute;ll m&oacute;dunkban a kapcsolattart&aacute;si adatok val&oacute;dis&aacute;g&aacute;nak ellenőrz&eacute;se &eacute;s annak meg&aacute;llap&iacute;t&aacute;sa sem, hogy a megadott adatok mag&aacute;nszem&eacute;lyre vagy v&aacute;llalkoz&aacute;sra vonatkoznak. A vel&uuml;nk kapcsolatba l&eacute;pő v&aacute;llalkoz&aacute;sokat &uuml;gyf&eacute;l partnerk&eacute;nt kezelj&uuml;k.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;s c&eacute;lja&nbsp;szakmai ismertetők, rekl&aacute;mot tartalmaz&oacute; elektronikus &uuml;zenetek, inform&aacute;ci&oacute;k, h&iacute;rlevelek k&uuml;ld&eacute;se, amelyekről b&aacute;rmikor k&ouml;vetkezm&eacute;nyek n&eacute;lk&uuml;l leiratkozhat. &Ouml;n akkor is minden k&ouml;vetkezm&eacute;ny n&eacute;lk&uuml;l leiratkozhat, ha v&aacute;llalkoz&aacute;sa idők&ouml;zben megszűnt, a v&aacute;llalkoz&aacute;sb&oacute;l kil&eacute;pett, vagy valaki az &Ouml;n kapcsolattart&aacute;si adatait k&ouml;z&ouml;lte vel&uuml;nk.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;s jogalapja&nbsp;az &Ouml;n hozz&aacute;j&aacute;rul&aacute;sa. T&aacute;j&eacute;koztatjuk, hogy a felhaszn&aacute;l&oacute; előzetesen &eacute;s kifejezetten hozz&aacute;j&aacute;rulhat ahhoz, hogy a szolg&aacute;ltat&oacute; rekl&aacute;maj&aacute;nlataival, t&aacute;j&eacute;koztat&aacute;saival &eacute;s egy&eacute;b k&uuml;ldem&eacute;nyeivel a regisztr&aacute;ci&oacute;kor megadott e-mail c&iacute;men megkeresse. Ennek k&ouml;vetkezt&eacute;ben a felhaszn&aacute;l&oacute; hozz&aacute;j&aacute;rulhat ahhoz, hogy a szolg&aacute;ltat&oacute; e c&eacute;lb&oacute;l a sz&uuml;ks&eacute;ges szem&eacute;lyes adatait kezelje.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">T&aacute;j&eacute;koztatjuk, ha h&iacute;rlevelet szeretne kapni től&uuml;nk, a sz&uuml;ks&eacute;ges adatokat k&ouml;teles megadni. Az adatszolg&aacute;ltat&aacute;s elmarad&aacute;sa eset&eacute;n nem tudunk &Ouml;nnek h&iacute;rlevelet k&uuml;ldeni.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;s időtartama:&nbsp;Az adatkezel&eacute;s a hozz&aacute;j&aacute;rul&aacute;s visszavon&aacute;s&aacute;ig t&ouml;rt&eacute;nik. Az adatkezel&eacute;shez t&ouml;rt&eacute;nő hozz&aacute;j&aacute;rul&aacute;s&aacute;t &Ouml;n b&aacute;rmikor visszavonhatja a kapcsolattart&aacute;si e-mail c&iacute;mre k&uuml;ld&ouml;tt lev&eacute;lben.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatok t&ouml;rl&eacute;se az adatkezel&eacute;shez t&ouml;rt&eacute;nő hozz&aacute;j&aacute;rul&aacute;s visszavon&aacute;sakor t&ouml;rt&eacute;nik meg. &Ouml;n b&aacute;rmikor visszavonhatja az adatkezel&eacute;shez t&ouml;rt&eacute;nő hozz&aacute;j&aacute;rul&aacute;s&aacute;t a kapcsolattart&aacute;si e-mail c&iacute;mre k&uuml;ld&ouml;tt lev&eacute;lben.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Ugyancsak visszavonhat&oacute; a hozz&aacute;j&aacute;rul&aacute;s a kik&uuml;ld&ouml;tt h&iacute;rlevelekben megjelenő link alapj&aacute;n.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatok megismer&eacute;s&eacute;re jogosultak:&nbsp;az adatkezelő &eacute;s alkalmazottai.<br>Az adatok t&aacute;rol&aacute;si m&oacute;dja:&nbsp;elektronikus.<br>Az adatok m&oacute;dos&iacute;t&aacute;sa vagy t&ouml;rl&eacute;se&nbsp;kezdem&eacute;nyezhető e-mailben, telefonon vagy lev&eacute;lben a fentebb megadott el&eacute;rhetős&eacute;gi lehetős&eacute;geken.<br>Az ig&eacute;nybe vett adatfeldolgoz&oacute;, illetve t</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);background-color: white;">&aacute;rhelyszolg&aacute;ltat&oacute;:</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);"><br><span style="background-color: white;">Paragon Internet Group Limited</span></span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&nbsp;</span></p>
<table border="0" cellpadding="0" cellspacing="0" style="width: 552.5pt;border-collapse: collapse;" width="737">
    <tbody>
        <tr>
            <td style="border: 1pt solid rgb(170, 170, 170);background-color: whitesmoke;padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-family: "Times New Roman", serif;'>Kezelt adatok k&ouml;re</span></strong></p>
            </td>
            <td style="border-top-width: 1pt;border-right-width: 1pt;border-bottom-width: 1pt;border-style: solid solid solid none;border-top-color: rgb(170, 170, 170);border-right-color: rgb(170, 170, 170);border-bottom-color: rgb(170, 170, 170);background-color: whitesmoke;padding: 3.75pt;background-position: initial initial;background-repeat: initial initial;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><strong><span style='font-family: "Times New Roman", serif;'>&nbsp;Az adatkezel&eacute;si adatok konkr&eacute;t c&eacute;lja</span></strong></p>
            </td>
        </tr>
        <tr>
            <td style="border-right-width: 1pt;border-bottom-width: 1pt;border-left-width: 1pt;border-style: none solid solid;border-right-color: rgb(170, 170, 170);border-bottom-color: rgb(170, 170, 170);border-left-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>N&eacute;v</span></p>
            </td>
            <td style="border-style: none solid solid none;border-bottom-width: 1pt;border-bottom-color: rgb(170, 170, 170);border-right-width: 1pt;border-right-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>Azonos&iacute;t&aacute;s, kapcsolattart&aacute;s</span></p>
            </td>
        </tr>
        <tr>
            <td style="border-right-width: 1pt;border-bottom-width: 1pt;border-left-width: 1pt;border-style: none solid solid;border-right-color: rgb(170, 170, 170);border-bottom-color: rgb(170, 170, 170);border-left-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>&nbsp;Email</span></p>
            </td>
            <td style="border-style: none solid solid none;border-bottom-width: 1pt;border-bottom-color: rgb(170, 170, 170);border-right-width: 1pt;border-right-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>Azonos&iacute;t&aacute;s, kapcsolattart&aacute;s&nbsp;</span></p>
            </td>
        </tr>
        <tr>
            <td style="border-right-width: 1pt;border-bottom-width: 1pt;border-left-width: 1pt;border-style: none solid solid;border-right-color: rgb(170, 170, 170);border-bottom-color: rgb(170, 170, 170);border-left-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>&nbsp;Feliratkoz&aacute;s időpontja</span></p>
            </td>
            <td style="border-style: none solid solid none;border-bottom-width: 1pt;border-bottom-color: rgb(170, 170, 170);border-right-width: 1pt;border-right-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>Technikai inform&aacute;ci&oacute;s művelet</span></p>
            </td>
        </tr>
        <tr>
            <td style="border-right-width: 1pt;border-bottom-width: 1pt;border-left-width: 1pt;border-style: none solid solid;border-right-color: rgb(170, 170, 170);border-bottom-color: rgb(170, 170, 170);border-left-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>&nbsp;IP c&iacute;m</span></p>
            </td>
            <td style="border-style: none solid solid none;border-bottom-width: 1pt;border-bottom-color: rgb(170, 170, 170);border-right-width: 1pt;border-right-color: rgb(170, 170, 170);padding: 3.75pt;">
                <p style='margin:0cm;font-size:16px;font-family:"Calibri",sans-serif;'><span style='font-family: "Times New Roman", serif;'>Technikai inform&aacute;ci&oacute;s művelet</span></p>
            </td>
        </tr>
    </tbody>
</table>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">T&aacute;j&eacute;koztatjuk, hogy az e-mail c&iacute;m eset&eacute;ben nem sz&uuml;ks&eacute;ges, hogy az a szem&eacute;ly&eacute;re utal&oacute; adatot tartalmazzon. &Iacute;gy p&eacute;ld&aacute;ul nem sz&uuml;ks&eacute;ges, hogy az e-mail c&iacute;m az &Ouml;n nev&eacute;t tartalmazza. &Ouml;n teljesen szabadon d&ouml;nt arr&oacute;l, hogy ha olyan e-mail c&iacute;met ad meg, amely az &Ouml;n kil&eacute;t&eacute;re utal&oacute; inform&aacute;ci&oacute;t tartalmaz. Az e-mail c&iacute;m - ami a kapcsolattart&aacute;st szolg&aacute;lja - felt&eacute;tlen&uuml;l sz&uuml;ks&eacute;ges ahhoz, hogy az &Ouml;n r&eacute;sz&eacute;re k&uuml;ld&ouml;tt h&iacute;rlev&eacute;l vagy szakmai inform&aacute;ci&oacute; c&eacute;lba &eacute;rjen.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">8. AZ ADATFELDOLGOZ&Aacute;SRA JOGOSULT SZEM&Eacute;LY</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A szem&eacute;lyes adatok feldolgoz&aacute;s&aacute;ra jogosult szem&eacute;ly a&nbsp;</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);background-color: white;">Paragon Internet Group Limited</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&nbsp;( Sz&eacute;khely:&nbsp;</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);background-color: white;">The Old Vinyl Factory, Hayes UB3 1HA, Egyes&uuml;lt Kir&aacute;lys&aacute;g</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">, a tov&aacute;bbiakban: Adatfeldolgoz&oacute;), mint Adatfeldolgoz&oacute;. A feldolgoz&aacute;sra ker&uuml;lő szem&eacute;lyes adatokat az Adatfeldolgoz&oacute; mindenkori t&ouml;rv&eacute;nyes k&eacute;pviselője(i), alkalmazottai/ megb&iacute;zottai/k&ouml;zreműk&ouml;dői ismerhetik meg. Az adatfeldolgoz&oacute; szem&eacute;lyes adatot harmadik szem&eacute;lyek r&eacute;sz&eacute;re nem ad &aacute;t, kiz&aacute;r&oacute;lag abban az esetben, ha az &eacute;rintett ehhez kifejezetten hozz&aacute;j&aacute;rul.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);"><br><strong>T&aacute;rhelyszolg&aacute;ltat&oacute;</strong></span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">N&eacute;v/c&eacute;gn&eacute;v:&nbsp;</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);">Paragon Internet Group Limited</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);"><br>Sz&eacute;khely:&nbsp;</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(46, 46, 46);">The Old Vinyl Factory, Hayes UB3 1HA, Egyes&uuml;lt Kir&aacute;lys&aacute;g</span><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);"><br>Telefon: +36 20 414 0284<br>E-mail: office@paprikasoft.com</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az &Ouml;n &aacute;ltal megadott adatokat a t&aacute;rhelyszolg&aacute;ltat&oacute; &aacute;ltal &uuml;zemeltetett szerver t&aacute;rolja. Az adatokhoz csak munkat&aacute;rsaink, illetve a szervert &uuml;zemeltető munkat&aacute;rsak f&eacute;rhetnek hozz&aacute;, de mindannyian felelőss&eacute;ggel tartoznak az adatok biztons&aacute;gos kezel&eacute;s&eacute;&eacute;rt.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A tev&eacute;kenys&eacute;g megnevez&eacute;se:&nbsp;t&aacute;rhelyszolg&aacute;ltat&aacute;s, szerverszolg&aacute;ltat&aacute;s.<br>Az adatkezel&eacute;s c&eacute;lja:&nbsp;a weboldal műk&ouml;d&eacute;s&eacute;nek biztos&iacute;t&aacute;sa.<br>A kezelt adatok:&nbsp;az &eacute;rintett &aacute;ltal megadott szem&eacute;lyes adatok</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;s időtartama &eacute;s az adatok t&ouml;rl&eacute;s&eacute;nek hat&aacute;rideje:&nbsp;Az adatkezel&eacute;s a weboldal műk&ouml;d&eacute;s&eacute;nek v&eacute;g&eacute;ig, illetve a weboldal műk&ouml;dtetője &eacute;s a t&aacute;rhelyszolg&aacute;ltat&oacute; k&ouml;z&ouml;tti szerződ&eacute;ses meg&aacute;llapod&aacute;s szerint. Az &eacute;rintett szem&eacute;ly sz&uuml;ks&eacute;g eset&eacute;n a t&aacute;rhelyszolg&aacute;ltat&oacute;t megkeresve is k&eacute;rheti adatai t&ouml;rl&eacute;s&eacute;t.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;s jogalapja:&nbsp;az &eacute;rintett szem&eacute;ly hozz&aacute;j&aacute;rul&aacute;sa, illetve jogszab&aacute;lyon alapul&oacute; adatkezel&eacute;s.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">9. AZ ADATKEZEL&Eacute;S IDŐTARTAMA</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A Felhaszn&aacute;l&oacute; hozz&aacute;j&aacute;rul&aacute;sa alapj&aacute;n megadott szem&eacute;lyes adatokat az Adatkezelő az adatkezel&eacute;s c&eacute;lj&aacute;nak megval&oacute;sul&aacute;s&aacute;ig, illetőleg a Felhaszn&aacute;l&oacute; hozz&aacute;j&aacute;rul&aacute;sa visszavon&aacute;s&aacute;ig kezeli. Az Adatkezelő a Felhaszn&aacute;l&oacute; regisztr&aacute;ci&oacute;ja sor&aacute;n megadott szem&eacute;lyes adatait a Weblap ig&eacute;nybev&eacute;tel&eacute;nek megszűn&eacute;s&eacute;ig, &iacute;gy k&uuml;l&ouml;n&ouml;sen a regisztr&aacute;ci&oacute; t&ouml;rl&eacute;s&eacute;ig kezeli.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő a felvett szem&eacute;lyes adatokat t&ouml;rv&eacute;ny elt&eacute;rő rendelkez&eacute;s&eacute;nek hi&aacute;ny&aacute;ban a) a r&aacute; vonatkoz&oacute; jogi k&ouml;telezetts&eacute;g teljes&iacute;t&eacute;se c&eacute;lj&aacute;b&oacute;l, vagy b) az adatkezelő vagy harmadik szem&eacute;ly jogos &eacute;rdek&eacute;nek &eacute;rv&eacute;nyes&iacute;t&eacute;se c&eacute;lj&aacute;b&oacute;l, ha ezen &eacute;rdek &eacute;rv&eacute;nyes&iacute;t&eacute;se a szem&eacute;lyes adatok v&eacute;delm&eacute;hez fűződő jog korl&aacute;toz&aacute;s&aacute;val ar&aacute;nyban &aacute;ll tov&aacute;bbi k&uuml;l&ouml;n hozz&aacute;j&aacute;rul&aacute;s n&eacute;lk&uuml;l, valamint az &eacute;rintett hozz&aacute;j&aacute;rul&aacute;s&aacute;nak visszavon&aacute;s&aacute;t k&ouml;vetően is kezelheti. / 2011. &eacute;vi CXII. t&ouml;rv&eacute;ny 6. &sect; ( 5) /</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő a Felhaszn&aacute;l&oacute; &aacute;ltal megadott szem&eacute;lyes adatokat a sz&aacute;mviteli k&ouml;telezetts&eacute;gek teljes&iacute;t&eacute;se &eacute;rdek&eacute;ben a 2000. &eacute;vi C. t&ouml;rv&eacute;ny 169.&sect;-a alapj&aacute;n 8 &eacute;vig, illetve az ad&oacute;z&aacute;s rendj&eacute;ről sz&oacute;l&oacute; 2003. &eacute;vi XCII. t&ouml;rv&eacute;nyben meghat&aacute;rozott el&eacute;v&uuml;l&eacute;si időn bel&uuml;l őrzi meg &eacute;s kezeli.&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">10. ADATTOV&Aacute;BB&Iacute;T&Aacute;S, ADATOK &Ouml;SSZEKAPCSOL&Aacute;SA &nbsp;</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő nem ad el, nem ad b&eacute;rbe &eacute;s semmilyen form&aacute;ban nem bocs&aacute;jt rendelkez&eacute;s&eacute;re a Felhaszn&aacute;l&oacute;ra vonatkoz&oacute; szem&eacute;lyes adatokat illetve inform&aacute;ci&oacute;kat m&aacute;s c&eacute;gnek, mag&aacute;nszem&eacute;lynek.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az Adatkezelő a tőle elv&aacute;rhat&oacute; m&oacute;don gondoskodik az adatok megfelelő biztons&aacute;g&aacute;r&oacute;l, &eacute;s megteszi azokat a technikai &eacute;s szervez&eacute;si int&eacute;zked&eacute;seket, melyek az adatv&eacute;delmi szab&aacute;lyok &eacute;s elvek &eacute;rv&eacute;nyre juttat&aacute;s&aacute;t garant&aacute;lj&aacute;k &eacute;s a szem&eacute;lyes adatok biztons&aacute;g&aacute;t előseg&iacute;tik.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">T&aacute;j&eacute;koztatjuk a Tisztelt Felhaszn&aacute;l&oacute;kat arr&oacute;l, hogy az Adatkezelő szem&eacute;lyes adatot kiz&aacute;r&oacute;lag az &eacute;rintett hozz&aacute;j&aacute;rul&aacute;s&aacute;val tov&aacute;bb&iacute;t harmadik szem&eacute;lynek vagy szem&eacute;lyeknek.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">11. S&Uuml;TIK (COOKIE-K)</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A s&uuml;tiket a megl&aacute;togatott weboldalak helyezik el a felhaszn&aacute;l&oacute; sz&aacute;m&iacute;t&oacute;g&eacute;p&eacute;n &eacute;s olyan inform&aacute;ci&oacute;t tartalmaznak, mint p&eacute;ld&aacute;ul az oldal be&aacute;ll&iacute;t&aacute;sai vagy a bejelentkez&eacute;s &aacute;llapota.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A cookie-k teh&aacute;t a felkeresett weboldalak &aacute;ltal l&eacute;trehozott kis f&aacute;jlok. A b&ouml;ng&eacute;sz&eacute;si adatok ment&eacute;s&eacute;vel jav&iacute;tj&aacute;k a felhaszn&aacute;l&oacute;i &eacute;lm&eacute;nyt. A cookie-k seg&iacute;ts&eacute;g&eacute;vel a weboldal eml&eacute;kezik a webhely be&aacute;ll&iacute;t&aacute;saira, &eacute;s helyileg relev&aacute;ns tartalmakat k&iacute;n&aacute;l fel.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A weblap l&aacute;togat&oacute;inak sz&aacute;m&iacute;t&oacute;g&eacute;p&eacute;re a szolg&aacute;ltat&oacute; weboldala egy kis f&aacute;jlt (cookie) k&uuml;ld annak &eacute;rdek&eacute;ben, hogy a l&aacute;togat&aacute;s t&eacute;nye &eacute;s ideje meg&aacute;llap&iacute;that&oacute; legyen. Erről a szolg&aacute;ltat&oacute; a weblap l&aacute;togat&oacute;j&aacute;t t&aacute;j&eacute;koztatja.&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatkezel&eacute;sben &eacute;rintettek k&ouml;re:&nbsp;a weboldal l&aacute;togat&oacute;i.<br>Az adatkezel&eacute;s c&eacute;lja:&nbsp;t&ouml;bbletszolg&aacute;ltat&aacute;s, azonos&iacute;t&aacute;s, a l&aacute;togat&oacute;k nyomon k&ouml;vet&eacute;se.<br>Az adatkezel&eacute;s jogalapja:&nbsp;A felhaszn&aacute;l&oacute; hozz&aacute;j&aacute;rul&aacute;sa nem sz&uuml;ks&eacute;ges, amennyiben a s&uuml;tik haszn&aacute;lat&aacute;hoz a szolg&aacute;ltat&oacute;nak felt&eacute;tlen&uuml;l sz&uuml;ks&eacute;ge van.<br>Az adatok k&ouml;re:&nbsp;egyedi azonos&iacute;t&oacute;sz&aacute;m, időpont, be&aacute;ll&iacute;t&aacute;si adatok.<br>A felhaszn&aacute;l&oacute;nak lehetős&eacute;ge van arra, hogy a s&uuml;tiket a Be&aacute;ll&iacute;t&aacute;sok men&uuml;pontban b&aacute;rmikor t&ouml;r&ouml;lje a b&ouml;ng&eacute;szőkből.<br>Az adatok megismer&eacute;s&eacute;re jogosult adatkezelők:&nbsp;A s&uuml;tik haszn&aacute;lat&aacute;val nem kezel szem&eacute;lyes adatokat az adatkezelő.<br>Az adatok t&aacute;rol&aacute;si m&oacute;dja:&nbsp;elektronikus.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">12. K&Ouml;Z&Ouml;SS&Eacute;GI OLDALAK</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A k&ouml;z&ouml;ss&eacute;gi oldal egy m&eacute;diaeszk&ouml;z, ahol az &uuml;zenetet k&ouml;z&ouml;ss&eacute;gi felhaszn&aacute;l&oacute;kon kereszt&uuml;l terjesztik. A k&ouml;z&ouml;ss&eacute;gi m&eacute;dia az internetet &eacute;s az online megjelen&eacute;si lehetős&eacute;geket haszn&aacute;lja annak &eacute;rdek&eacute;ben, hogy a felhaszn&aacute;l&oacute;k tartalombefogad&oacute;kb&oacute;l tartalomszerkesztőv&eacute; v&aacute;ljanak.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A k&ouml;z&ouml;ss&eacute;gi m&eacute;dia az internetes alkalmaz&aacute;sok olyan fel&uuml;lete, amelyen a felhaszn&aacute;l&oacute;k &aacute;ltal l&eacute;trehozott tartalom tal&aacute;lhat&oacute;, p&eacute;ld&aacute;ul Facebook, Google+, Twitter, stb.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A k&ouml;z&ouml;ss&eacute;gi m&eacute;dia megjelen&eacute;si form&aacute;i lehetnek nyilv&aacute;nos besz&eacute;dek, előad&aacute;sok, bemutat&oacute;k, term&eacute;kek vagy szolg&aacute;ltat&aacute;sok ismertet&eacute;se.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A k&ouml;z&ouml;ss&eacute;gi m&eacute;di&aacute;ban megjelent inform&aacute;ci&oacute;k form&aacute;i lehetnek f&oacute;rumok, blogbejegyz&eacute;sek, k&eacute;p-, vide&oacute;-, &eacute;s hanganyagok, &uuml;zenőfalak, e-mail &uuml;zenetek, stb.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A fentieknek megfelelően a kezelt adatok k&ouml;re a szem&eacute;lyes adatokon t&uacute;l lehet a felhaszn&aacute;l&oacute; nyilv&aacute;nos profilk&eacute;pe is.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az &eacute;rintettek k&ouml;re:&nbsp;valamennyi regisztr&aacute;lt felhaszn&aacute;l&oacute;.<br>Az adatgyűjt&eacute;s c&eacute;lja&nbsp;a weboldal vagy a hozz&aacute; kapcsol&oacute;d&oacute; weblap n&eacute;pszerűs&iacute;t&eacute;se.<br>Az adatkezel&eacute;s jogalapja&nbsp;az &eacute;rintett &ouml;nk&eacute;ntes hozz&aacute;j&aacute;rul&aacute;sa.<br>Az adatkezel&eacute;s időtartama:&nbsp;az adott k&ouml;z&ouml;ss&eacute;gi oldalon megtekinthető szab&aacute;lyoz&aacute;s szerint.<br>Az adatok t&ouml;rl&eacute;si hat&aacute;rideje:&nbsp;az adott k&ouml;z&ouml;ss&eacute;gi oldalon megtekinthető szab&aacute;lyoz&aacute;s szerint.<br>Az adatok megismer&eacute;s&eacute;re jogosultak:&nbsp;az adott k&ouml;z&ouml;ss&eacute;gi oldalon megtekinthető szab&aacute;lyoz&aacute;s szerint.<br>Az adatkezel&eacute;ssel kapcsolatos jogok:&nbsp;az adott k&ouml;z&ouml;ss&eacute;gi oldalon megtekinthető szab&aacute;lyoz&aacute;s szerint.<br>Az adatok t&aacute;rol&aacute;si m&oacute;dja: elektronikus.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Fontos figyelembe venni, hogy amikor a felhaszn&aacute;l&oacute; felt&ouml;lt vagy bek&uuml;ld valamilyen szem&eacute;lyes adatot, vil&aacute;gszerte &eacute;rv&eacute;nyes enged&eacute;lyt ad a k&ouml;z&ouml;ss&eacute;gi oldal &uuml;zemeltetőj&eacute;nek arra, hogy az ilyen tartalmakat t&aacute;rolhassa &eacute;s felhaszn&aacute;lhassa. Ez&eacute;rt nagyon fontos meggyőződni arr&oacute;l, hogy a k&ouml;zz&eacute;tett inform&aacute;ci&oacute; k&ouml;zl&eacute;s&eacute;hez a felhaszn&aacute;l&oacute; teljes jogosults&aacute;ggal rendelkezik-e.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">13. GOOGLE ANALYTICS</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Weboldalunk a Google Analytics alkalmaz&aacute;st haszn&aacute;lja.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Google Analytics alkalmaz&aacute;sa eset&eacute;n</span></strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">:</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A Google Analytics belső cookie-k (s&uuml;tik) alapj&aacute;n &aacute;ll&iacute;t &ouml;ssze jelent&eacute;st &uuml;gyfelei r&eacute;sz&eacute;re a weblap felhaszn&aacute;l&oacute;inak szok&aacute;sair&oacute;l.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A weboldal &uuml;zemeltetőj&eacute;nek megb&iacute;z&aacute;s&aacute;b&oacute;l a Google az inform&aacute;ci&oacute;kat arra haszn&aacute;lja, hogy ki&eacute;rt&eacute;kelje, hogyan haszn&aacute;lj&aacute;k a felhaszn&aacute;l&oacute;k a honlapot. Tov&aacute;bbi szolg&aacute;ltat&aacute;sk&eacute;nt a honlap aktivit&aacute;s&aacute;val &ouml;sszef&uuml;ggő jelent&eacute;seket k&eacute;sz&iacute;t weboldal &uuml;zemeltetőj&eacute;nek r&eacute;sz&eacute;re, hogy az tov&aacute;bbi szolg&aacute;ltat&aacute;sokat teljes&iacute;thessen.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatokat a Google szerverei k&oacute;dolt form&aacute;tumban t&aacute;rolj&aacute;k, hogy megnehez&iacute;ts&eacute;k &eacute;s elej&eacute;t vegy&eacute;k az adatokkal val&oacute; vissza&eacute;l&eacute;snek.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A Google Analytics letilt&aacute;sa az al&aacute;bbiak szerint t&ouml;rt&eacute;nhet. Id&eacute;zet az oldalr&oacute;l:</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><em><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Azok a webhelyfelhaszn&aacute;l&oacute;k, akik nem szeretn&eacute;k, hogy a Google Analytics JavaScript jelent&eacute;st k&eacute;sz&iacute;tsen az adataikr&oacute;l, telep&iacute;thetik a Google Analytics letilt&oacute; b&ouml;ng&eacute;szőbőv&iacute;tm&eacute;ny&eacute;t. A bőv&iacute;tm&eacute;ny megtiltja a Google Analytics JavaScript (ga.js, analytics.js, &eacute;s dc.js) sz&aacute;m&aacute;ra, hogy inform&aacute;ci&oacute;kat k&uuml;ldj&ouml;n a Google Analytics rendszernek. A b&ouml;ng&eacute;szőbőv&iacute;tm&eacute;ny a legt&ouml;bb &uacute;jabb b&ouml;ng&eacute;szőben haszn&aacute;lhat&oacute;. A Google Analytics letilt&oacute; b&ouml;ng&eacute;szőbőv&iacute;tm&eacute;nye nem akad&aacute;lyozza meg az adatk&uuml;ld&eacute;st maga a webhely &eacute;s m&aacute;s internetes elemz&eacute;si szolg&aacute;ltat&aacute;sok r&eacute;sz&eacute;re.</span></em></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><a href="https://support.google.com/analytics/answer/6004245?hl=hu" target="_blank"><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(0, 122, 197);">https://support.google.com/analytics/answer/6004245?hl=hu</span></a></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A Google adatv&eacute;delmi ir&aacute;nyelvei:&nbsp;</span><a href="https://policies.google.com/privacy?hl=hu" target="_blank"><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(0, 122, 197);">https://policies.google.com/privacy?hl=hu</span></a></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az adatok felhaszn&aacute;l&aacute;s&aacute;val &eacute;s v&eacute;delm&eacute;vel kapcsolatos inform&aacute;ci&oacute;k r&eacute;szletesen a fenti hivatkoz&aacute;sokon &eacute;rhetők el.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">14. ADATV&Eacute;DELEM R&Eacute;SZLETESEN</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><a href="https://static.googleusercontent.com/media/www.google.com/en/intl/hu/policies/privacy/google_privacy_policy_hu.pdf" target="_blank"><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(0, 122, 197);">https://static.googleusercontent.com/media/www.google.com/en//intl/hu/policies/privacy/google_privacy_policy_hu.pdf</span></a></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">15. AZ ADATKEZEL&Eacute;SSEL KAPCSOLATOS JOGOK</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A t&aacute;j&eacute;koztat&aacute;s k&eacute;r&eacute;shez val&oacute; jog</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&Ouml;n a megadott el&eacute;rhetős&eacute;geken kereszt&uuml;l t&aacute;j&eacute;koztat&aacute;st k&eacute;rhet től&uuml;nk, hogy c&eacute;g&uuml;nk milyen adatait, milyen jogalapon, milyen adatkezel&eacute;si c&eacute;l miatt, milyen forr&aacute;sb&oacute;l, mennyi ideig kezeli. Az &Ouml;n k&eacute;relm&eacute;re halad&eacute;ktalanul, de legfeljebb 30 napon bel&uuml;l, az &Ouml;n &aacute;ltal megadott e-mail el&eacute;rhetős&eacute;gre t&aacute;j&eacute;koztat&aacute;st k&uuml;ld&uuml;nk.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A helyesb&iacute;t&eacute;shez val&oacute; jog</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&Ouml;n a megadott el&eacute;rhetős&eacute;geken kereszt&uuml;l k&eacute;rheti től&uuml;nk hogy valamely adat&aacute;t m&oacute;dos&iacute;tsuk. Erről az &Ouml;n k&eacute;relm&eacute;re halad&eacute;ktalanul, de legfeljebb 30 napon bel&uuml;l int&eacute;zked&uuml;nk, az &Ouml;n &aacute;ltal megadott e-mail el&eacute;rhetős&eacute;gre t&aacute;j&eacute;koztat&aacute;st k&uuml;ld&uuml;nk.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A t&ouml;rl&eacute;shez val&oacute; jog</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&Ouml;n a megadott el&eacute;rhetős&eacute;geken kereszt&uuml;l k&eacute;rheti től&uuml;nk adat&aacute;nak t&ouml;rl&eacute;s&eacute;t. Az &Ouml;n k&eacute;relm&eacute;re ezt halad&eacute;ktalanul, de legfeljebb 30 napon bel&uuml;l megtessz&uuml;k, az &Ouml;n &aacute;ltal megadott e-mail el&eacute;rhetős&eacute;gre t&aacute;j&eacute;koztat&aacute;st k&uuml;ld&uuml;nk.&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A z&aacute;rol&aacute;shoz val&oacute; jog</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&Ouml;n a megadott el&eacute;rhetős&eacute;geken kereszt&uuml;l k&eacute;rheti től&uuml;nk adat&aacute;nak z&aacute;rol&aacute;s&aacute;t. A z&aacute;rol&aacute;s addig tart, am&iacute;g az &Ouml;n &aacute;ltal megjel&ouml;lt indok sz&uuml;ks&eacute;gess&eacute; teszi az adatok t&aacute;rol&aacute;s&aacute;t. Az &Ouml;n k&eacute;relm&eacute;re ezt halad&eacute;ktalanul, de legfeljebb 30 napon bel&uuml;l megtessz&uuml;k, az &Ouml;n &aacute;ltal megadott e-mail el&eacute;rhetős&eacute;gre t&aacute;j&eacute;koztat&aacute;st k&uuml;ld&uuml;nk.&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">A tiltakoz&aacute;shoz val&oacute; jog</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&Ouml;n a megadott el&eacute;rhetős&eacute;geken kereszt&uuml;l tiltakozhat az adatkezel&eacute;s ellen. A tiltakoz&aacute;st a k&eacute;relem beny&uacute;jt&aacute;s&aacute;t&oacute;l sz&aacute;m&iacute;tott legr&ouml;videbb időn bel&uuml;l, de legfeljebb 15 napon bel&uuml;l megvizsg&aacute;ljuk, annak megalapozotts&aacute;ga k&eacute;rd&eacute;s&eacute;ben d&ouml;nt&eacute;st hozunk, &eacute;s a d&ouml;nt&eacute;s&eacute;ről &Ouml;nt e-mailben t&aacute;j&eacute;koztatjuk.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">16. AZ ADATKEZEL&Eacute;SSEL KAPCSOLATOS JOG&Eacute;RV&Eacute;NYES&Iacute;T&Eacute;SI LEHETŐS&Eacute;G</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Az &Ouml;n &aacute;ltal tapasztalt jogellenes adatkezel&eacute;s eset&eacute;n &eacute;rtes&iacute;tse c&eacute;g&uuml;nket, &iacute;gy lehetős&eacute;g ny&iacute;lik arra, hogy r&ouml;vid időn bel&uuml;l helyre&aacute;lljon a jogszerű &aacute;llapot. Az &Ouml;n &eacute;rdek&eacute;ben mindent megtesz&uuml;nk, hogy a v&aacute;zolt probl&eacute;ma megold&oacute;djon.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Amennyiben az &Ouml;n meg&iacute;t&eacute;l&eacute;se szerint a jogszerű &aacute;llapot nem &aacute;ll&iacute;that&oacute; helyre, &eacute;rtes&iacute;tse erről a hat&oacute;s&aacute;got az al&aacute;bbi el&eacute;rhetős&eacute;geken:</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><strong><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Nemzeti Adatv&eacute;delmi &eacute;s Inform&aacute;ci&oacute;szabads&aacute;g Hat&oacute;s&aacute;g</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Postac&iacute;m: 1530 Budapest, Pf.: 5.<br>C&iacute;m: 1125 Budapest, Szil&aacute;gyi Erzs&eacute;bet fasor 22/c <br>Telefon: +36 (1) 391-1400 <br>Fax: +36 (1) 391-1410 <br>E-mail: ugyfelszolgalat (kukac) naih.hu <br>URL https://naih.hu <br>Koordin&aacute;t&aacute;k: &Eacute; 47&deg;30&apos;56&apos;&apos;; K 18&deg;59&apos;57&apos;&apos;&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><strong><span style="font-size:24px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">17. AZ ADATKEZEL&Eacute;S ALAPJ&Aacute;UL SZOLG&Aacute;L&Oacute; JOGSZAB&Aacute;LYOK</span></strong></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- AZ EUR&Oacute;PAI PARLAMENT &Eacute;S A TAN&Aacute;CS (EU) 2016/679 RENDELETE (2016. &aacute;prilis 27.) a term&eacute;szetes szem&eacute;lyeknek a szem&eacute;lyes adatok kezel&eacute;se tekintet&eacute;ben t&ouml;rt&eacute;nő v&eacute;delm&eacute;ről &eacute;s az ilyen adatok szabad &aacute;raml&aacute;s&aacute;r&oacute;l, valamint a 95/46/EK rendelet hat&aacute;lyon k&iacute;v&uuml;l helyez&eacute;s&eacute;ről (&aacute;ltal&aacute;nos adatv&eacute;delmi rendelet).</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- 2011. &eacute;vi CXII. t&ouml;rv&eacute;ny az inform&aacute;ci&oacute;s &ouml;nrendelkez&eacute;si jogr&oacute;l &eacute;s az inform&aacute;ci&oacute;szabads&aacute;gr&oacute;l.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- A k&ouml;ziratokr&oacute;l, a k&ouml;zlev&eacute;lt&aacute;rakr&oacute;l &eacute;s a mag&aacute;nlev&eacute;lt&aacute;ri anyag v&eacute;delm&eacute;ről sz&oacute;l&oacute; 1995. &eacute;vi LXVI. t&ouml;rv&eacute;ny.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- A k&ouml;zfeladatot ell&aacute;t&oacute; szervek iratkezel&eacute;s&eacute;nek &aacute;ltal&aacute;nos k&ouml;vetelm&eacute;nyeiről sz&oacute;l&oacute; 335/2005. (XII. 29.) Korm. rendelet.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- 2001. &eacute;vi CVIII. t&ouml;rv&eacute;ny az elektronikus kereskedelmi szolg&aacute;ltat&aacute;sok, valamint az inform&aacute;ci&oacute;s t&aacute;rsadalommal &ouml;sszef&uuml;ggő szolg&aacute;ltat&aacute;sok egyes k&eacute;rd&eacute;seiről.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">- 2003. &eacute;vi C. t&ouml;rv&eacute;ny az elektronikus h&iacute;rk&ouml;zl&eacute;sről.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;margin-bottom: 7.5pt;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">&nbsp;</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;background-color: white;'><span style="font-size:14px;font-family: Arial, sans-serif;color: rgb(51, 51, 51);">Jelen Adatv&eacute;delmi Nyilatkozat hat&aacute;lyba l&eacute;p&eacute;s&eacute;nek időpontja: 2020.12.07. Az adatkezelő a v&aacute;ltoztat&aacute;s jog&aacute;t fenntartja.</span></p>
<p style='margin:0cm;font-size: medium;font-family:"Calibri",sans-serif;'>&nbsp;</p>
</body>
</html>
